/*
Steel Data SQL Challenge 1 - Steve's Car Showroom

 Skills Used: Temp Table, Joins, Aggregate Functions, Converting Data Types
*/

-- 1. What are the details of all cars purchased in the year 2022?

SELECT *
FROM cars AS car
JOIN sales AS sal
ON car.car_id = sal.car_id
WHERE YEAR(purchase_date)= 2022

-- 2. What is the total number of cars sold by each salesperson?

SELECT name, COUNT (sale_id) AS cars_sold
FROM sales AS sal
JOIN salespersons AS person
ON sal.salesman_id = person.salesman_id
GROUP BY name

-- 3. What is the total revenue generated by each salesperson?

SELECT salesman_id, SUM(cost_$) AS total_revenue
FROM cars AS ca
JOIN sales AS sal
ON ca.car_id = sal.car_id
GROUP BY salesman_id
ORDER BY 1,2 DESC

-- 4. What are the details of the cars sold by each salesperson?

SELECT salesman_id, make, type, style
FROM cars AS ca
JOIN sales AS sal
ON ca.car_id = sal.car_id

-- 5. What is the total revenue generated by each car type?

-- Temp Table

DROP TABLE IF exists #cars_total_revenue
CREATE TABLE #cars_total_revenue
(
type nvarchar(50),
car_id numeric,
cost_$ numeric
);

INSERT INTO #cars_total_revenue
SELECT
type,
cost_$ AS cost,
COUNT (sal.car_id) AS qty
FROM
sales AS sal
JOIN cars AS ca
ON ca.car_id = sal.car_id
GROUP BY type, cost_$

/* final output */

SELECT type, SUM(cost_$)*SUM(car_id) AS total_revenue
FROM #cars_total_revenue
GROUP BY type
ORDER BY 1;


-- 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

SELECT make, type, style
FROM cars AS ca
JOIN sales AS sal
ON ca.car_id = sal.car_id
WHERE YEAR(purchase_date)= 2021
AND sal.salesman_id = 2 -- Emily Wong has salesman_id of 2
 
-- 7. What is the total revenue generated by the sales of hatchback cars?

SELECT style, SUM(cost_$) AS total_revenue
FROM cars AS ca
JOIN sales AS sal
ON sal.car_id = ca.car_id
WHERE style = 'hatchback'
GROUP BY style
ORDER BY 1

-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?

SELECT style, SUM(cost_$) AS total_revenue
FROM cars AS ca
JOIN sales AS sal
ON sal.car_id = ca.car_id
WHERE style = 'SUV'
AND YEAR(purchase_date)= 2022
GROUP BY style
ORDER BY 1

-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?

SELECT name, city
FROM sales AS sal
JOIN salespersons AS per
ON sal.salesman_id = per.salesman_id
WHERE YEAR(purchase_date) = 2023
GROUP BY name, city
ORDER BY COUNT(car_id) DESC

-- 10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?

SELECT name, age
FROM sales AS sal
JOIN salespersons AS per
ON sal.salesman_id = per.salesman_id
JOIN cars AS ca
ON sal.car_id = ca.car_id
WHERE YEAR(purchase_date)= 2022
GROUP BY name, age
ORDER BY SUM(cost_$) DESC
